package DTOS;

public enum CodigoResultado {

    PUEDE_ELIMINARSE,
    TIENE_FACTURAS,
    RESPONSABLE_NO_ENCONTRADO,

    ELIMINADO,

    AUTENTICADO,
    CREDENCIALES_INVALIDAS,

    DATOS_INCOMPLETOS,
    NOMBRE_USUARIO_INVALIDO,
    PASSWORD_LONGITUD,
    PASSWORD_NUMEROS_CONSECUTIVOS,
    USUARIO_YA_EXISTE,
    USUARIO_NO_EXISTE,
    ULTIMO_USUARIO,
    USUARIO_SESION_ACTUAL,
    USUARIO_CREADO,
    USUARIO_ELIMINADO,
    ERROR_INESPERADO
}
